@version: 4.2

@include "scl.conf"
@include "scl/kafka/kafka.conf"

# ----------------------------------------------------
# 1. INPUTS: UDP 5514 + TCP 6514
# ----------------------------------------------------
source s_network {
    udp(ip("0.0.0.0") port(5514));
    tcp(ip("0.0.0.0") port(6514));
};

# ----------------------------------------------------
# 2. PARSER: RFC5424
# ----------------------------------------------------
parser p_syslog {
    syslog-parser();
};

# ----------------------------------------------------
# 3. JSON Formatter
# ----------------------------------------------------
template t_json {
    template("$(format-json --scope all-nv-pairs)\n");
};

# ----------------------------------------------------
# 4. KAFKA DESTINATION
# ----------------------------------------------------
destination d_kafka {
    kafka-c(
        bootstrap-servers("kafka:9092")
        topic("syslog_raw")
        template(t_json)
    );
};

# ----------------------------------------------------
# 5. PIPELINE
# ----------------------------------------------------
log {
    source(s_network);
    parser(p_syslog);
    destination(d_kafka);
};
